services:
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=weerayuth
      - POSTGRES_USER=weerayuth
      - POSTGRES_PASSWORD=weerayuth
  app:
    image: prawee/strapi:latest
    container_name: my_app_compose
    ports:
      - "8081:1337"
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=172.16.58.138
      - DATABASE_PORT=55432
      - DATABASE_USERNAME=weerayuth
      - DATABASE_PASSWORD=weerayuth
      - DATABASE_SSL=false